[workspace]
members = ["contracts/*", "packages/*"]

[profile.release.package.badge-hub]
codegen-units = 1
incremental = false

[profile.release.package.badge-nft]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
