[package]
name        = "badges"
version     = "1.0.0"
authors     = ["larry <gm@larry.engineer>"]
edition     = "2021"
description = "Badges allows anyone to create digital badges, as rewards for participantion in events or achieving certain accomplishments"
readme      = "README.md"
homepage    = "https://larry.engineer"
repository  = "https://github.com/st4k3h0us3/badges"
license     = "GPL-3.0-or-later"
keywords    = ["nft", "cosmos", "cosmwasm", "stargaze"]

[lib]
doctest = false

[dependencies]
cosmwasm-std = "1.0"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
# TODO: update once published on crates.io
sg-metadata = { git = "https://github.com/public-awesome/launchpad", rev = "c5280ef" }
